#!/usr/bin/env ruby
#
# Create a website from:
#  - plain html template files
#  - markdown content files
#  - nokogiri content insertion

require './static_site_generator'
require 'redcarpet'
require 'nokogiri'
require 'pp'


class TemplateProcessor

  def self.process_template raw_template, all_metadata
    PROCESSORS.reduce( Nokogiri::HTML.parse(raw_template) ) do | memo, func |
      func.call(memo, all_metadata)
    end
  end

  PROCESSORS = [

    ->(template, metadata) do
      if template.at_css(".blog-posts")
        blog_meta = metadata[:content_directories].find {|dir| dir[:filename] == 'blog.content'}
        pp blog_meta

        # blog_meta[:content_files].map { |memo, file_meta|
        #   {
        #     href: '/' + filename,
        #     name: file_meta[:teaser_name],
        #     summary: file_meta[:teaser_summary],
        #     date: file_meta[:date],
        #     year: file_meta[:date].year
        #   }
        # }.sort { |a,b| -(a[:date] <=> b[:date]) }


        #squirt blog posts into sidebar
      end
      template # pass straight through for now
    end
  ]
end


class ContentProcessor

  def self.content_file? filename
    return filename.end_with? '.md'
  end

  def self.process_content markdown, template, file_meta
    PROCESSORS.reduce( templated_content(markdown, template) ) do | memo, func |
      func.call(memo, file_meta)
    end
  end

  def self.templated_content markdown, template
    # Important? Do not alter cached copy. Clone.
    template = template.clone

    main = template.at_css("main")
    main.content = ""
    main.add_child(
      Redcarpet::Markdown.new(Redcarpet::Render::HTML.new).render(markdown)
    )

    template
  end

  PROCESSORS = [

    # Set the head title element.
    ->(content, file_meta) do
      title = content.at_css("html head title")
      tpl_title = title.content
      suffix = tpl_title[tpl_title.index(' | ')..-1]
      title.content = file_meta[:'html-head-title'] + suffix
      content
    end,

    # Set the active menu option
    ->(content, file_meta) do
      case file_meta[:template]
      when 'home.template.html'
        menu_item = content.at_css('#top-menu a[href="/"]')
      when 'page.template.html'
        menu_item = content.at_css("#top-menu a[href='/#{file_meta[:filename].chomp('.md')}']")
      when 'blog.template.html'
        menu_item = content.at_css('#top-menu a[href="/blog"]')
      end
      menu_item.set_attribute('is-active', 'true') if menu_item
      content
    end

  ]
end


ssg = StaticSiteGenerator.new TemplateProcessor, ContentProcessor
ssg.generate Dir.pwd + "/input", Dir.pwd + "/output", Dir.pwd + "/templates"
